"""add: description to meal

Revision ID: c24357b40807
Revises: 4cdda7d3bef3
Create Date: 2024-02-17 21:05:13.225510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24357b40807'
down_revision = '4cdda7d3bef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('description', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'description')
    # ### end Alembic commands ###
